### PR TITLE
Corrected subtitle level for some global_options; Increased auto generated index depth level by 1.

### PR DESCRIPTION
**Pull request by y-he2**
Please note that there are 2 changes in this PR:
1. Corrected the subtitle level for: PolarOpts, DatasetTransformOpts and EmphasisOpts.
2. Could we show a deeper subtitle level in the index? This would decrease the scrolling when searching for specific subtitles for items with many of them, eg pyecharts.GraphicGroup. If this feels too much feel free to revert this change.

https://pyecharts.org/#/en-us/global_options
https://pyecharts.org/#/zh-cn/global_options

### CODE REVIEW

**Comment by sunhailin-Leo** [comment]
@y-he2 
* Are there any other similar errors in the docs? If so please correct them all, thanks!

**Comment by y-he2** [comment]
So far I have only see these 2 places, but I will make sure to correct them if I see more. Feel free to close this one first and I can check when I have time. Thank you!

**Comment by sunhailin-Leo** [comment]
> So far I have only see these 2 places, but I will make sure to correct them if I see more. Feel free to close this one first and I can check when I have time. Thank you!

I will keep pr open for 2 weeks and if there are no updates by then I`ll merge it. If you have something to add, you can commit it on this pr.

**Comment by y-he2** [comment]
Sound good!

**Comment by y-he2** [comment]
I have checked through all other titles in ZH and EN, the original commit seem to be the only place with that kind of copy-paste errors.

**Pull request merged**
