### PR TITLE
Fix the document link, it has been tested

### PR DESCRIPTION
**Pull request by he-zhiyuan**

### CODE REVIEW

**Comment by sunhailin-Leo** [comment]
@he-weilai 
* Why modify these contents?

**Comment by he-weilai** [comment]
@sunhailin-Leo Due to the addition of "zh cn" in the path, it is not possible to jump normally, but I should not add the suffix ".md"

**Comment by he-zhiyuan** [comment]
@sunhailin-Leo Due to the addition of "zh-cn" in the path, it is not possible to jump normally, but I should not add the suffix ".md"

**Comment by sunhailin-Leo** [comment]
> @sunhailin-Leo Due to the addition of "zh-cn" in the path, it is not possible to jump normally, but I should not add the suffix ".md"

* You can check the website `https://pyecharts.org/#/`, I think it isn`t a problem on the path.

**Comment by he-weilai** [comment]
@sunhailin-Leo OK

**Comment by he-zhiyuan** [comment]
@sunhailin-Leo OK，thank you

**Comment by sunhailin-Leo** [comment]
> @sunhailin-Leo OK， thank you

* Closed it. If you find another disabled link, you can make the new pr here.

**Pull request closed without merging**
